apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cocreate-ws-deployment
      labels:
        app: cocreate-ws
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: cocreate-ws
      template:
        metadata:
          labels:
            app: cocreate-ws
            # gitcommit: ${CICD_GIT_COMMIT}
        spec:
          containers:
            - name: cocreate-ws
            # replace with your image name 
              image: frankpagan/cocreatews:latest
              ports:
                - containerPort: 8081

  - apiVersion: v1
    kind: Service
    metadata:
      name: cocreate-ws-service
    spec:
      selector:
        app: cocreate-ws
      ports:
        - name: app
          protocol: TCP
          port: 8081
          targetPort: 8081

  - apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      name: cocreate-ws-ingress
      annotations:
        nginx.ingress.kubernetes.io/proxy-read-timeout: 3600
        nginx.ingress.kubernetes.io/proxy-send-timeout: 3600
    spec:
      rules:
        - host: ws.cocreate.app
          http:
            paths:
              - path: /
                backend:
                  serviceName: cocreate-ws-service
                  servicePort: 8081