apiVersion: v1
kind: Service
metadata:
  name: cocreatews
  namespace: default
spec:
  ports:
    - name: app
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: cocreatews

  sessionAffinity: None
  type: ClusterIP
