name: Docker Build Push

on:
  push:
    branches: 
    - develop
    - newtest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Build and push Docker image
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
        repository: ${{ secrets.DOCKERHUB_USER }}/cocreatews
        tags: ${{ github.sha }}, latest, ${{ steps.extract_branch.outputs.branch }}
#     - name: Image digest
#       run: echo ${{ steps.docker_push.outputs.digest }}
