name: Docker Build Push

on:
  push:
    branches: 
    - develop
    - newtest 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: ${{ secrets.DOCKERHUB_USER }}/cocreatews
        tags: ${{ github.sha }}, latest,${GITHUB_REF##*/}
#     - name: Image digest
#       run: echo ${{ steps.docker_push.outputs.digest }}
