name: Publish docker image

on:
  push:
    tags: 
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      IMAGE: docker.pkg.github.com/cocreate-app/cocreatews/cocreatews
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Login docker registry
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
    - name: Build docker image
      run: docker build . -t $IMAGE:latest -t $IMAGE:${GITHUB_REF:10}
    - name: Push docker image
      run: |
        docker push $IMAGE:latest
        docker push $IMAGE:${GITHUB_REF:10}
    - name: Get kubectl
      run: |
        curl -LO https://dl.k8s.io/release/v1.20.0/bin/linux/amd64/kubectl
        chmod +x kubectl
    - name: Generate deployment
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        sed -i "s/IMAGE_TAG/${GITHUB_REF:10}/g" k8s/kustomization.yaml
        ./kubectl kustomize k8s/ > manifests/temp.yaml
        git stash
        git checkout master
        mv manifests/temp.yaml manifests/k8sfile.yml
        git add manifests/k8sfile.yml
        git commit -m "update manifest file"
        git push "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/CoCreate-app/CoCreateWS.git" master -f
      

